### ISSUE TITLE
API interface: return pointers to objects instead of full-blown structs

### ISSUE THREAD

**Issue by unleashed** [3scale/3scale-go-client#3]
As discussed in https://github.com/3scale/3scale-go-client/pull/2#discussion_r230714932 we are currently returning structs in some places (that is an instance of an API response object) where we can have just pointers.

This issue is about moving our interface (wherever possible) to return pointers instead of structs to avoid extra allocations and force callers to check for errors.

**Comment by PhilipGough** [comment]
Closed with latest refactor
